services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ".env"
  db:
    image: 'mariadb'
    env_file:
      - ".env"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: {}